# CREDIT SCORING MODEL

---

**Algorithms Used & Tested:**
- Logistic Regression
- **Decision Tree Classifier**
- Random Forest Classifier
- Gradient Boosting Classifier

---

> **Note:** This Model Was Not Trained On Any Real Data.

### LOAD DATASET

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("D:/intern/Data/credit_data.csv")
df = df.drop_duplicates()
df.head()

,Age,Annual_Income,Employment_Years,Monthly_Debt,Debt_to_Income,Credit_Utilization,Late_Payments,Credit_History_Years,Credit_Accounts,Loan_Amount,Previous_Defaults,Payment_History_Score,Home_Ownership,Marital_Status,Education_Level,Creditworthy
0,43.0,120000.0,12.0,2150.0,0.22,28.0,0.0,18,6,24000.0,0.0,94.0,Own,Married,Bachelor,1
1,29.0,48000.0,6.0,950.0,0.24,38.0,1.0,7,4,5000.0,0.0,90.0,Rent,Single,HighSchool,1
2,55.0,95000.0,30.0,1200.0,0.15,22.0,0.0,34,10,18000.0,0.0,99.0,Mortgage,Married,Master,1
3,38.0,60000.0,10.0,1300.0,0.26,45.0,2.0,14,5,15000.0,0.0,85.0,Rent,Single,Bachelor,1
4,27.0,37000.0,3.0,800.0,0.25,40.0,1.0,5,3,7000.0,0.0,92.0,Rent,Single,HighSchool,1

### SPLITTING

In [2]:
from sklearn.model_selection import train_test_split
X = df.drop("Creditworthy", axis=1)
y = df["Creditworthy"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

---
### IMPORTING LIBRARIES
---
#### PIPELINE,IMPUTER,SCALER,ENCODER,COLUMN-TRANSFORMER

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

### SET CATEGORICAL & NUMERICAL PIPELINE

In [4]:
categorical_pipeline = Pipeline([
    ("imputer",SimpleImputer(strategy="most_frequent")),
    ("encoder",OneHotEncoder(handle_unknown="ignore"))
])

numerical_pipeline = Pipeline([
    ("imputer",SimpleImputer(strategy="mean")),
    ("scaler",StandardScaler())
])

### DEFINING CATEGORICAL & NUMERICAL COLUMNS

In [5]:
cat_cols = X.select_dtypes(include="object").columns
num_cols = X.select_dtypes(include="number").columns

C:\Users\SAURODEEP DE\AppData\Local\Temp\ipykernel_10012\289984206.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X.select_dtypes(include="object").columns

### SET COLUMN-TRANSFORMER

In [6]:
preprocessor = ColumnTransformer([
    ("categorical",categorical_pipeline,cat_cols),
    ("numerical",numerical_pipeline,num_cols)
])

---
### IMPORTING ALGORITHMS
---
#### Logistic Regression, Decision Tree Classifier, Random Forest Classifier, Gradient Boosting Classifier

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

### SET MODELS AND PREPROCESSOR IN PIPELINE

In [8]:
model_log_reg = Pipeline([
    ("preprocessor",preprocessor),
    ("log_reg",LogisticRegression())
])

model_dec_tree = Pipeline([
    ("preprocessor",preprocessor),
    ("dec_tree",DecisionTreeClassifier())
])

model_rand_forest = Pipeline([
    ("preprocessor",preprocessor),
    ("rand_forest",RandomForestClassifier())
])

model_grad_boost = Pipeline([
    ("preprocessor",preprocessor),
    ("grad_boost",GradientBoostingClassifier())
])

---
### IMPORT METRICES
--- 
#### Accuracy score,Precision score, Recall score, F1 score

In [9]:
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score

### IMPORT CROSS-VALIDATOR

In [10]:
from sklearn.model_selection import cross_validate,StratifiedKFold

---
### CROSS VALIDATION
---

#### SPLITTING CROSS-VALIDATION
#### CROSS VALIDATING DIFFERENT METRICES FOR EACH ALGORITHM:
- Accuracy score,
- Precision score, 
- Recall score, 
- F1 score

In [11]:
cv = StratifiedKFold(
    n_splits = 5,
    shuffle = True,
    random_state=42
)

scores_log_reg = cross_validate(
    model_log_reg,
    X_train,
    y_train,
    cv=cv,
    scoring=["accuracy", "precision", "recall", "f1"]
)


Accuracy_log_reg = scores_log_reg["test_accuracy"].mean()
Precision_log_reg =scores_log_reg["test_precision"].mean()
Recall_log_reg = scores_log_reg["test_recall"].mean()
F1_log_reg = scores_log_reg["test_f1"].mean()

scores_dec_tree = cross_validate(
    model_dec_tree,
    X_train,
    y_train,
    cv=cv,
    scoring=["accuracy", "precision", "recall", "f1"]
)

Accuracy_dec_tree = scores_dec_tree["test_accuracy"].mean()
Precision_dec_tree =scores_dec_tree["test_precision"].mean()
Recall_dec_tree = scores_dec_tree["test_recall"].mean()
F1_dec_tree = scores_dec_tree["test_f1"].mean()

scores_rand_forest = cross_validate(
    model_rand_forest,
    X_train,
    y_train,
    cv=cv,
    scoring=["accuracy", "precision", "recall", "f1"]
)

Accuracy_rand_forest = scores_rand_forest["test_accuracy"].mean()
Precision_rand_forest =scores_rand_forest["test_precision"].mean()
Recall_rand_forest = scores_rand_forest["test_recall"].mean()
F1_rand_forest = scores_rand_forest["test_f1"].mean()

scores_grad_boost = cross_validate(
    model_grad_boost,
    X_train,
    y_train,
    cv=cv,
    scoring=["accuracy", "precision", "recall", "f1"]
)

Accuracy_grad_boost = scores_grad_boost["test_accuracy"].mean()
Precision_grad_boost =scores_grad_boost["test_precision"].mean()
Recall_grad_boost = scores_grad_boost["test_recall"].mean()
F1_grad_boost = scores_grad_boost["test_f1"].mean()

### CREATING A DATAFRAME OF THE RESULTS

In [12]:
cv_df = pd.DataFrame({
    "Model":["Log Reg","Dec Tree","Rand_Forest","Grad Boost"],
    "Accuracy":[Accuracy_log_reg,Accuracy_dec_tree,Accuracy_rand_forest,Accuracy_grad_boost],
    "Precision":[Precision_log_reg,Precision_dec_tree,Precision_rand_forest,Precision_grad_boost],
    "Recall":[Recall_log_reg,Recall_dec_tree,Recall_rand_forest,Recall_grad_boost],
    "F1":[F1_log_reg,F1_dec_tree,F1_rand_forest,F1_grad_boost]
})

cv_df

         Model  Accuracy  Precision   Recall        F1
0      Log Reg  0.995506   0.997297  0.99726  0.997260
1     Dec Tree  0.997753   1.000000  0.99726  0.998621
2  Rand_Forest  0.995506   0.997297  0.99726  0.997260
3   Grad Boost  0.995506   0.997297  0.99726  0.997260

### OVERFITTING TEST FOR THE BEST ALGORITHM

In [13]:
scores_overfit_test = cross_validate(
    model_dec_tree,
    X_train,
    y_train,
    cv=cv,
    scoring="accuracy",
    return_train_score=True
)

print("Train:", scores_overfit_test["train_score"].mean())
print("Validation:", scores_overfit_test["test_score"].mean())

Train: 1.0
Validation: 0.995505617977528

In [14]:
print("Got the highest (0.997753) Accuracy with Decision Tree Classifire Algorithm using 5-Folds of Cross Validation")
print("Tested for any overfitting with accuracy validation and train score. Which clearly shows there is no sign of overfitting")

Got the highest (0.997753) Accuracy with Decision Tree Classifire Algorithm using 5-Folds of Cross Validation
Tested for any overfitting with accuracy validation and train score. Which clearly shows there is no sign of overfitting

### FITTING THE BEST ALGORITHM

In [15]:
model_dec_tree.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['Home_Ownership', 'Marital_Status', 'Education_Level'], dtype='str')),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['Age', 'Annual_Income', 'Employment_Years', 'Monthly_Debt',
       'Debt_to_Income', 'Credit_Utilization', 'Late_Payments',
       'Credit_History_Years', 'Credit_Accounts', 'Loan_Amount',
       'Previous_Defaults', 'Payment_History_Score'],
      dtype='str'))])),
                ('dec_tree', DecisionTreeClassifier())])

### PREDICT

In [16]:
y_pred_dec_tree = model_dec_tree.predict(X_test)

### METRICES

In [17]:
acc_dec_tree = accuracy_score(y_test,y_pred_dec_tree)
prec_dec_tree = precision_score(y_test,y_pred_dec_tree)
rec_dec_tree = recall_score(y_test,y_pred_dec_tree)
f1_dec_tree = f1_score(y_test,y_pred_dec_tree)

In [18]:
print("Accuracy:",acc_dec_tree)
print("Precision:",prec_dec_tree)
print("Recall:",rec_dec_tree)
print("F1:",f1_dec_tree)

Accuracy: 0.9947643979057592
Precision: 0.9935483870967742
Recall: 1.0
F1: 0.9967637540453075

### SAVE MODEL

In [19]:
import joblib

joblib.dump(model_dec_tree,"D:/intern/Model/Decision_tree_Pipeline.pkl")

['D:/intern/Model/Decision_tree_Pipeline.pkl']